COPY INTO ANGEL_CITY_HEALTH_DB.RAW.PATIENTS_RAW
(
    PATIENT_DATA,
    SOURCE_FILE_NAME,
    FILE_ROW_NUMBER,
    FILE_LAST_MODIFIED
)
FROM
(
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_LAST_MODIFIED
    FROM @ANGEL_CITY_HEALTH_DB.RAW.ANGEL_CITY_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = 'ANGEL_CITY_HEALTH_DB.RAW.JSON_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;
