COPY_INTO_BRONZE = """
COPY INTO LONESTAR_PROD_DB.BRONZE.LONESTAR_DAILY_LOAD
    (LONESTAR_DATA, SOURCE_FILE_NAME, FILE_ROW_NUMBER, FILE_LAST_MODIFIED)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_LAST_MODIFIED
    FROM @LONESTAR_PROD_DB.BRONZE.BRONZE_S3_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'LONESTAR_PROD_DB.BRONZE.JSON_S3_DAILY')
ON_ERROR = 'ABORT_STATEMENT';
"""
